var data = {
  words: [
    "persistent",
    "well-modulated",
    "exuding",
    "monitoring",
    "cohesive",
    "right-sized",
    "realigned",
    "strategy",
    "Mandatory",
    "Multi-lateral",
    "multi-tasking",
    "assimilated",
    "focus group",
    "open system",
    "analyzer",
    "responsive",
    "object-oriented",
    "advanced",
    "encompassing",
    "front-line",
    "up-sized",
    "devolved",
    "multi-channelled",
    "protocol",
    "stand-alone",
    "universal",
    "attitude",
    "zero tolerance",
    "innovative",
    "proactive",
    "public-key",
    "success",
    "homogeneous",
    "data-warehouse",
    "approach",
    "context-sensitive",
    "solution-oriented",
    "human-resource",
    "multi-layered",
    "reverse-engineered",
    "open-architected",
    "context-sensitive",
    "operative",
    "synergistic",
    "focus group",
    "functionalities",
    "future-proofed",
    "24 hour",
    "definition",
    "installation",
    "quality-focused",
    "customer loyalty",
    "moratorium",
    "automated",
    "grass-roots",
    "task-force",
    "protocol",
    "foreground",
    "content-based",
    "core",
    "frame",
    "access",
    "vision-oriented",
    "object-based",
    "demand-driven",
    "solution-oriented",
    "solution",
    "polarised",
    "architecture",
    "paradigm",
    "persistent",
    "optional",
    "optional",
    "portal",
    "dynamic",
    "vision-oriented",
    "ability",
    "discrete",
    "success",
    "re-contextualized",
    "proactive",
    "versatile",
    "exuding",
    "support",
    "foreground",
    "progressive",
    "diverse",
    "actuating",
    "tangible",
    "operative",
    "assimilated",
    "adaptive",
    "proactive",
    "strategy",
    "support",
    "regional",
    "switchable",
    "zero tolerance",
    "user-facing",
    "function"
  ]
};
module.exports = data;
